---

- name: "Download calicoctl"
  get_url:
      url: https://github.com/projectcalico/calicoctl/releases/download/v3.4.0/calicoctl
      dest: /usr/local/bin/calicoctl
      mode: 0775
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true

# - pause:
#     seconds: 60
- name: Wait for ETCD to become available
  wait_for:
    host: 192.168.36.136
    port: 6666
    delay: 10
    state: started

- name: "Create ippool"
  command: "calicoctl create -f /vagrant/roles/cni/templates/{{ item }}"
  environment:
    ETCD_ENDPOINTS: "http://192.168.36.136:6666"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  # ignore_errors: true
  with_items:
    - ip-pool1.yml
    - ip-pool2.yml

- name: "Create namespace"
  shell: kubectl --kubeconfig={{ kubeadmin_config }} create -f /vagrant/roles/cni/templates/{{ item }}
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  # ignore_errors: true
  with_items:
    - namespace-test1.yml
    - namespace-test2.yml

- name: "BGP default configuration"
  command: "calicoctl create -f /vagrant/roles/cni/templates/bgp_default.yml"
  environment:
    ETCD_ENDPOINTS: "http://192.168.36.136:6666"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  # ignore_errors: true


- name: "BGP peer setup"
  command: "calicoctl create -f /vagrant/roles/cni/templates/bgp_peer.yml"
  environment:
    ETCD_ENDPOINTS: "http://192.168.36.136:6666"
  delegate_to: "{{ groups['master'][0] }}"
  run_once: true
  # ignore_errors: true
